### ISSUE TITLE
Armv8 on IzzyOnDroid

### ISSUE THREAD

**Issue by machiav3lli** [LittleTrickster/PDF-Doc-Scan#10]
@IzzySoft would you please replace the armv7 apks with armv8?
Thanks!

**Comment by IzzySoft** [comment]
@LittleTrickster you're OK with that? It would make the app unavailable to all 32bit devices. The advantages are mostly a possible little performance boost on arm64 devices, and that the app became available to those poor users with Google Pixel 7 plus :speak_no_evil:

PS: An alternative might be a build just covering both ARM ABIs (and only those). That should be less than 15 MB in size, so I still could keep 2 versions available in my repo.

**Comment by LittleTrickster** [comment]
@IzzySoft I think you should use the arm64 version. 
I haven't found a simple way to build another apk with two ABIs after splitting.

**Comment by LittleTrickster** [comment]
Using flavours does work. But it takes ages to build since it does compile, R8, minify and etc... for each individual apk.

`assembleRelease`

```
   flavorDimensions "abi"
    productFlavors {
        universal {
            dimension "abi"
            ndk {
                abiFilters "armeabi-v7a", "arm64-v8a", "x86_64", "x86"
            }
        }
        x86 {
            dimension "abi"
            ndk {
                abiFilters "x86"
            }
        }
        x86_64 {
            dimension "abi"
            ndk {
                abiFilters "x86_64"
            }
        }
        armeabi_v7a {
            dimension "abi"
            ndk {
                abiFilters "armeabi-v7a"
            }
        }
        arm64_v8a {
            dimension "abi"
            ndk {
                abiFilters "arm64-v8a"
            }
        }
        arm {
            dimension "abi"
            ndk {
                abiFilters "armeabi-v7a", "arm64-v8a"
            }
        }
    }
```

**Comment by IzzySoft** [comment]
I'd leave the decision to you. If you say it should be arm64, I'll prepare the switch. If you don't mind the compile time, I can take the "double arm" one (btw, what size did it turn out to be?).

**Comment by LittleTrickster** [comment]
@IzzySoft  Added [1.03](https://github.com/LittleTrickster/PDF-Doc-Scan/releases/tag/1.03) with `app-arm-release.apk` ~15MB for both "armeabi-v7a", "arm64-v8a" just use this one.

**Comment by IzzySoft** [comment]
Thanks! That way neither party can complain (except for size). Still fits in my repo twice, so it's set to keep the current and the previous version.

Btw: would you mind establishing Fastlane structures in your repo here, so you'd be in control of description, graphics etc (i.e. how your app is presented)? My updater would check that along when pulling new versions then. You're welcome to use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for guidance – and I could even offer you a PR with what's currently set up with my repo, as a starter-package so to say.

**Comment by machiav3lli** [comment]
Thank you both for your efforts!
