### ISSUE TITLE
[CXX1405] error when building with cmake using opencv\libcxx_helper\CMakeLists.txt: C++ build system [configure] failed while executing:

### ISSUE THREAD

**Issue by Office-Murtaza** [LittleTrickster/PDF-Doc-Scan#12]
@echo off
    "D:\\Sdk\\cmake\\3.18.1\\bin\\cmake.exe" ^
      "-HD:\\workspace\\danish\\opencv\\libcxx_helper" ^
      "-DCMAKE_SYSTEM_NAME=Android" ^
      "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON" ^
      "-DCMAKE_SYSTEM_VERSION=21" ^
      "-DANDROID_PLATFORM=android-21" ^
      "-DANDROID_ABI=x86" ^
      "-DCMAKE_ANDROID_ARCH_ABI=x86" ^
      "-DANDROID_NDK=D:\\Sdk\\ndk\\23.1.7779620" ^
      "-DCMAKE_ANDROID_NDK=D:\\Sdk\\ndk\\23.1.7779620" ^
      "-DCMAKE_TOOLCHAIN_FILE=D:\\Sdk\\ndk\\23.1.7779620\\build\\cmake\\android.toolchain.cmake" ^
      "-DCMAKE_MAKE_PROGRAM=D:\\Sdk\\cmake\\3.18.1\\bin\\ninja.exe" ^
      "-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=D:\\workspace\\danish\\opencv\\build\\intermediates\\cxx\\Debug\\5h324k5y\\obj\\x86" ^
      "-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=D:\\workspace\\danish\\opencv\\build\\intermediates\\cxx\\Debug\\5h324k5y\\obj\\x86" ^
      "-DCMAKE_BUILD_TYPE=Debug" ^
      "-BD:\\workspace\\danish\\opencv\\.cxx\\Debug\\5h324k5y\\x86" ^
      -GNinja ^
      "-DANDROID_STL=c++_shared"
Plz help me out to remove this compatibility errors.

**Comment by LittleTrickster** [comment]
Dunno much about this type of errors. The only difference I see is that you use `3.18.1` cmake version and mine is `3.22.1`. Might be older Android studio IDE. Also check env variables.
Tell me if it helps.

**Comment by Office-Murtaza** [comment]
I have change IDE CMake with 3.22.1 but again

[CXX1429] error when building with cmake using C:\Users\DE\Desktop\PDF-Doc-Scan-master\opencv\libcxx_helper\CMakeLists.txt: C++ build system [configure] failed while executing:
    @echo off
    "D:\\Sdk\\cmake\\3.22.1\\bin\\cmake.exe" ^
      "-HC:\\Users\\DE\\Desktop\\PDF-Doc-Scan-master\\opencv\\libcxx_helper" ^
      "-DCMAKE_SYSTEM_NAME=Android" ^
      "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON" ^
      "-DCMAKE_SYSTEM_VERSION=21" ^
      "-DANDROID_PLATFORM=android-21" ^
      "-DANDROID_ABI=arm64-v8a" ^
      "-DCMAKE_ANDROID_ARCH_ABI=arm64-v8a" ^
      "-DANDROID_NDK=D:\\Sdk\\ndk\\23.1.7779620" ^
      "-DCMAKE_ANDROID_NDK=D:\\Sdk\\ndk\\23.1.7779620" ^
      "-DCMAKE_TOOLCHAIN_FILE=D:\\Sdk\\ndk\\23.1.7779620\\build\\cmake\\android.toolchain.cmake" ^
      "-DCMAKE_MAKE_PROGRAM=D:\\Sdk\\cmake\\3.22.1\\bin\\ninja.exe" ^
      "-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\DE\\Desktop\\PDF-Doc-Scan-master\\opencv\\build\\intermediates\\cxx\\Debug\\5e1p6t2a\\obj\\arm64-v8a" ^
      "-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=C:\\Users\\DE\\Desktop\\PDF-Doc-Scan-master\\opencv\\build\\intermediates\\cxx\\Debug\\5e1p6t2a\\obj\\arm64-v8a" ^
      "-DCMAKE_BUILD_TYPE=Debug" ^
      "-BC:\\Users\\DE\\Desktop\\PDF-Doc-Scan-master\\opencv\\.cxx\\Debug\\5e1p6t2a\\arm64-v8a" ^
      -GNinja ^
      "-DANDROID_STL=c++_shared"
  from C:\Users\DE\Desktop\PDF-Doc-Scan-master\opencv

**Comment by Office-Murtaza** [comment]
Plz update the project with latest Android Studio Flamingo. i have consume too much time to build project but its create different types of building failed errors.

**Comment by LittleTrickster** [comment]
Are you talking about upgrading Android Gradle plugin? If so maybe your cache is corrupt when using older dependencies or maybe even SDK. I tested on 3 PCs that can compile it just fine. Also could be .idea folder problems you can just delete it. Well at least I'm glad it works now for you.

**Comment by Office-Murtaza** [comment]
[](url)[CXX1429] error when building with cmake using C:\Users\DE\Desktop\PDF-Doc-Scan-master\opencv\libcxx_helper\CMakeLists.txt: C++ build system [configure] failed while executing:
    @echo off
    "D:\\Sdk\\cmake\\3.22.1\\bin\\cmake.exe" ^
      "-HC:\\Users\\DE\\Desktop\\PDF-Doc-Scan-master\\opencv\\libcxx_helper" ^
      "-DCMAKE_SYSTEM_NAME=Android" ^
      "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON" ^
      "-DCMAKE_SYSTEM_VERSION=21" ^
      "-DANDROID_PLATFORM=android-21" ^
      "-DANDROID_ABI=x86" ^
      "-DCMAKE_ANDROID_ARCH_ABI=x86" ^
      "-DANDROID_NDK=D:\\Sdk\\ndk\\21.4.7075529" ^
      "-DCMAKE_ANDROID_NDK=D:\\Sdk\\ndk\\21.4.7075529" ^
      "-DCMAKE_TOOLCHAIN_FILE=D:\\Sdk\\ndk\\21.4.7075529\\build\\cmake\\android.toolchain.cmake" ^
      "-DCMAKE_MAKE_PROGRAM=D:\\Sdk\\cmake\\3.22.1\\bin\\ninja.exe" ^
      "-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\DE\\Desktop\\PDF-Doc-Scan-master\\opencv\\build\\intermediates\\cxx\\Debug\\2d385r1x\\obj\\x86" ^
      "-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=C:\\Users\\DE\\Desktop\\PDF-Doc-Scan-master\\opencv\\build\\intermediates\\cxx\\Debug\\2d385r1x\\obj\\x86" ^
      "-DCMAKE_BUILD_TYPE=Debug" ^
      "-BC:\\Users\\DE\\Desktop\\PDF-Doc-Scan-master\\opencv\\.cxx\\Debug\\2d385r1x\\x86" ^
      -GNinja ^
      "-DANDROID_STL=c++_shared"
  from C:\Users\DE\Desktop\PDF-Doc-Scan-master\opencv

i have delete .gradle and also delete the .idea but its not configure with cmake and ndk compatibility.
Cmake version=3.22.1
NDK Version=21.4.7075529

therefore i also delete build and cache from .android folder and many time invalidate cache and res
![buildconfiguration](https://github.com/LittleTrickster/PDF-Doc-Scan/assets/68837264/dde22906-a3b7-467f-a9d7-ca8b18fdf95f)
tart.
